name = "agenticaiaccounting"
main = "src/index.ts"
compatibility_date = "2025-03-14"
usage_model = "standard"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "agenticaiaccounting-db"
database_id = "2a4fa461-6163-4394-9ad1-3049d49a036c"

[[kv_namespaces]]
binding = "KV"
id = "bf47d4e3ebcf48dbaecb61d968a870fb"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[workflows]]
name = "agenticaiaccounting-pipeline"
binding = "PIPELINE_WORKFLOW"
class_name = "PipelineWorkflow"
